# Generated by Django 5.1.5 on 2026-02-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_reader_alter_books_id_bookassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookassignment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bookapp.books'),
        ),
        migrations.AlterField(
            model_name='bookassignment',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='bookapp.reader'),
        ),
    ]
